services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fraud-api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./artifacts:/app/artifacts
      - ./data:/app/data

  ui:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fraud-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./src:/app/src
      - ./artifacts:/app/artifacts
      - ./data:/app/data